name = "LatticeModels"
uuid = "ba061c01-2eed-4a80-a5f7-9f291138a0fe"
authors = ["Tomas S. Grigera <tgrigera@iflysib.unlp.edu.ar> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
